/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulpro.vista.dialogos;

import simulpro.modelo.logica.Bayes;
import simulpro.vista.componentes.beans.FactoryCellListRenderer;

/**
 *
 * @author sala de software
 */
public class DialogProbability extends RootDialog {

    
    private final Bayes BAYES = new Bayes();
    
    public DialogProbability(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listTipo = new javax.swing.JList<>();
        listTipo.setCellRenderer(FactoryCellListRenderer.createListCellRenderer());
        jScrollPane2 = new javax.swing.JScrollPane();
        listGenero = new javax.swing.JList<>();
        listGenero.setCellRenderer(FactoryCellListRenderer.createListCellRenderer());
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listTipo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "AGUA", "BEBIDAS CALIENTES", "BEBIDAS AZUCARADAS", "BEBIDAS NATURALES", "BEBIDAS LÁCTEAS", "COCIDOS", "DULCES", "HORNEADOS", "MECATOS", "FRITO" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listTipo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTipo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTipoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listTipo);

        listGenero.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "HOMBRE", "MUJER" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listGenero.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listGenero.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listGeneroValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listGenero);

        jLabel1.setText("Genero");

        jLabel2.setText("Tipo");

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textArea.setForeground(new java.awt.Color(0, 153, 255));
        textArea.setLineWrap(true);
        textArea.setRows(5);
        jScrollPane3.setViewportView(textArea);

        jLabel3.setText("Probabilidad");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listGeneroValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listGeneroValueChanged
        if(!listGenero.isSelectionEmpty() && !listTipo.isSelectionEmpty() && evt.getValueIsAdjusting()){
           String genero = listGenero.getSelectedValue();
           String producto = listTipo.getSelectedValue();
           String probabilidad = "La Prabilidad que compre "+producto+" y sean "+genero;
           probabilidad+= " "+BAYES.probabilidadCondicional(genero, producto);
           textArea.setText(probabilidad);
       }
    }//GEN-LAST:event_listGeneroValueChanged

    private void listTipoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTipoValueChanged
       if(!listGenero.isSelectionEmpty() && !listTipo.isSelectionEmpty() && evt.getValueIsAdjusting()){
           String genero = listGenero.getSelectedValue();
           String producto = listTipo.getSelectedValue();
           String probabilidad = "La Prabilidad que compre "+producto+" y sean "+genero;
           probabilidad+= " "+BAYES.probabilidadCondicional(genero, producto);
           textArea.setText(probabilidad);
       }
    }//GEN-LAST:event_listTipoValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listGenero;
    private javax.swing.JList<String> listTipo;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
